name: Solar System Workflow

on: 
  workflow_dispatch: #running manually
  push: #running on push happens on this 2 branch
    branches:
      - main
      - 'feature/*'
    
jobs:
    unit-testing:
        name: Unit Testing
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup NodeJS Version
          uses: actions/setup-node@v3
          with:
            node-version: 20
    
        - name: Install Dependencies
          run: npm install
    
        - name: Unit Testing
          run: npm test
          
        - name: Archive Test Result
          uses: actions/upload-artifact@4
          with:
            name: Mocha-Test-Result
            path: test-results.xml
    docker:
        name: containerization
        needs: unit-testing
        runs-on: ubuntu-latest
        steps:
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ vars.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: docker registry push
          uses: docker/build-push-action@v4
          with:
            context: .
            push: false # want push true means it will push to registry
            tags: |
                ${{vars.DOCKERHUB_USERNAME}}/solar-system:${{github.sha}}
        - name: dhcr login #github container registry
          uses: docker/login-action@  #ghcr login we use regular docker command also use docker login username is ghcr.io and password is github token
          with:
            registry: ghcr.io #by default docker will use docker registry so we are giving resgistry
            username: ${{github.repository_owner}}
            password: ${{ secrets.GITHUB_TOKEN }}
#next step is to build and push to github registry
        - name: Container registry push
          uses: docker/build-push-action@v4
          with:
            context: .
            push: true # want push true means it will push to registry
            tags: |
                ${{vars.DOCKERHUB_USERNAME}}/solar-system:${{github.sha}}  
                ghcr.io/${{github.repository_owner}}/solar-system:${{github.sha}}
#once taged it will push to both registries

